package com.ed.rules;

import com.hit.health.bindings.IndvInfo;
import com.hit.health.bindings.ElgDetails;

rule "Snap Plan Rules for AP"

	when
		indvInfo:IndvInfo(isEmployed=='N')
	then
			ElgDetails elgDetails = new ElgDetails();
			elgDetails.setPlanName("SNAP");
			elgDetails.setPlanStatus("AP");
			elgDetails.setPlanStartDate("04-04-2020");
			elgDetails.setPlanEndDate("04-07-2020");
			elgDetails.setBenefitAmount("$300.00");
			indvInfo.setElgDetails(elgDetails);
	end
rule "Snap Plan Rules for DN"

	when
		indvInfo:IndvInfo(isEmployed=='Y')
	then
			ElgDetails elgDetails = new ElgDetails();
			elgDetails.setPlanName("SNAP");
			elgDetails.setPlanStatus("DN");
			elgDetails.setDenialReson("High Income");
			indvInfo.setElgDetails(elgDetails);
	end
	